### ISSUE TITLE
Unable to migrate CREATE STORED PROCEDURE statements

### ISSUE THREAD

**Issue by BobDankert** [fluxoft/migrant#1]
I've been unable to figure out how to add stored procedures to a migration file. I'm guessing this is related to the parsing of the file, specifically as it relates to changing the delimiter as part of defining the procedure. Any help for adding this would be appreciated!

**Comment by BobDankert** [comment]
I figured out my own answer. Don't include any of the commands for changing the delimiter in the migrant file - just leave that out and keep using the standard semi-colon everywhere, and it is now working great! Thanks much for the tool.

**Comment by joe-hart** [comment]
Thanks for letting me know, Bob. I have personally only used migrant for importing table schemas, not stored procedures, so I hadn't run into this. If I get the time, I might see if I can figure out how to make migrant work with stored procedures like this one.
